### ISSUE TITLE
Error when creating environment using conda env create -f SpatialTE.yml

### ISSUE THREAD

**Issue by rpisalive** [bvaldebenitom/SpatialTE#2]
Hello there,
Thanks a lot for the effort and I would really love to try the pipeline to analyze some spatial data.

When I try to install evreything using the command conda env create -f SpatialTE.yml, it gives me the following error messages.
I tried to run it in a bash environment connected via ssh and run it locally on my computer, same thing happened.
The SpatialTE.yml is already in my working directory.

Could you advice what could be the potential problem?
Thanks a lot!

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 89, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/conda_env/env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/conda_env/env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/ruamel_yaml/main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/ruamel_yaml/composer.py", line 104, in compose_document
        self.parser.get_event()
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/ruamel_yaml/parser.py", line 163, in get_event
        self.current_event = self.state()
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/ruamel_yaml/parser.py", line 239, in parse_document_end
        token = self.scanner.peek_token()
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/ruamel_yaml/scanner.py", line 182, in peek_token
        self.fetch_more_tokens()
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/ruamel_yaml/scanner.py", line 282, in fetch_more_tokens
        return self.fetch_value()
      File "/opt/anaconda/anaconda3/lib/python3.8/site-packages/ruamel_yaml/scanner.py", line 651, in fetch_value
        raise ScannerError(
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 27, column 66:
         ... le" content="{&quot;groups&quot;: [], &quot;environmentKey&quot; ...
                                             ^ (line: 27)

`$ /opt/anaconda/anaconda3/bin/conda-env create -f SpatialTE.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
                CONDA_EXE=/opt/anaconda/anaconda3/bin/conda
         CONDA_PYTHON_EXE=/opt/anaconda/anaconda3/bin/python
               CONDA_ROOT=/opt/anaconda/anaconda3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                     PATH=/opt/anaconda/anaconda3/bin:/opt/anaconda/anaconda3/condabin:/usr/loca
                          l/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/mpang/.local/bin:/home/
                          mpang/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /home/mpang/.condarc
 populated config files : /home/mpang/.condarc
          conda version : 4.12.0
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/anaconda/anaconda3  (read only)
      conda av data dir : /opt/anaconda/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda/anaconda3/pkgs
                          /home/mpang/.conda/pkgs
       envs directories : /home/mpang/.conda/envs
                          /opt/anaconda/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.25.1 CPython/3.8.8 Linux/3.10.0-1160.53.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1011:1012
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

**Comment by bvaldebenitom** [comment]
Hi @rpisalive!

Do you have Miniconda available on your computer? 

I just tried it and it works as expected.

Best regards,
Braulio.
